### ISSUE TITLE
Add Token Type Spacer or Pre & Post Padding

### ISSUE THREAD

**Issue by wixregiga** [bendera/vscode-commit-message-editor#51] opened 2022-04-05 04:35 UTC
## Problems
1. Spacing is inconsistent using the Dynamic Template
2. Separator does not act as expected when using combination boxes

## Solutions
1. A Built-In Token type called SPACER. If you want functionality similar to this in linux: - `echo -e "subject line\n\nbody\n\nfooter"`. Require a `{SPACER}` token in the dynamic template.
2. There are a couple of solutions:
    a) Add {SPACER} as an acceptable separator
    b) When `multiple` is is selected, add a boolean field called `separate_lines` which defaults to false. If you set it to true the result would be each entry in the array being appended like this Linux command `echo -e "Line 1\nLine 2\nLine 3\nLine 4`. We wouldn't add `"\n"` to the last element in the array because we want the user to be explicit about the format. They could use `{SPACER}` in the Dynamic Template for it.

I can submit a PR on Friday if there isn't already one made

**Comment by bendera** [comment] 2022-04-13 09:22
Hi,

Sorry for the late response, I didn't notice this issue. The root cause is that the extension does auto-formatting and removes the extra newlines. I should remove this function. It seemed to be a good idea but it's not. if the auto-format didn't remove the extra whitespaces, modifying the commit template would be enough. So I will remove this function. Anyway, I'm planning to introduce a new wrap text feature.

**Comment by bendera** [comment] 2023-01-27 16:32
I will bump a new version soon. I'm still struggling with the wrap text function, so for now, I just delete the "unnecessary newlines removing" feature. 
Your second issue can be resolved by converting the single-line separator field to textarea.

**Closed** 2023-01-30 22:26 UTC
